name: Server Tests (Ruby)
on:
  push:
    branches:
      - main
      - fix-ci
  workflow_dispatch:
  pull_request_target:
    paths:
      - 'server/ruby/**'
      - '!**.md'

jobs:
  require-permission:
    uses: ./.github/workflows/require_permission.yml

  server_test:
    needs: require-permission
    strategy:
      fail-fast: false
      matrix:
        runtime:
          - server_type: ruby
            server_image: ruby:latest
          - server_type: ruby
            server_image: ruby:2.7
    uses: ./.github/workflows/server_test.yml
    secrets: inherit
    with:
      server_type: ${{ matrix.runtime.server_type }}
      server_image: ${{ matrix.runtime.server_image }}


  dependabot-auto-merge:
    if: ${{ github.event.pull_request && github.actor == 'dependabot[bot]' }}
    needs: server_test
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/dependabot.yml
    secrets: inherit
