
name: Require Permission

on:
  workflow_call:

env:
  MAINTAINERS: |
    cecilphillip-stripe
    charliegerard-stripe
    dependabot[bot]
    erinkavanaugh-stripe
    hideokamoto-stripe
    kevinpeters-stripe

jobs:
  require-permission:
    runs-on: ubuntu-latest
    steps:
      - name: 'check if the triggering actor is one of the maintainers'
        run: |
          while read -r item; do
            if [[ "$item" == "${{ github.triggering_actor }}" ]]; then
              exit 0 # safe to run tests with write permission
            fi
          done <<< "$MAINTAINERS"
          echo "CI have to be re-run by one of the $MAINTAINERS" >> "$GITHUB_STEP_SUMMARY"
          exit 1